module.exports = [
    {
        name: "Camaro Yenko/SC 427 Coupe",
        brand: "Revell",
        manufacturer: "Chevrolet",
        model: "Camaro",
        yearOfProduction: 1969,
        purchasePrice: 39.75,
        currentValue: 70, 
        preparedtoSell: true,
        qty: 1,
    },
    {
        name: "Challenger T/A 2'n1",
        brand: "Revell",
        manufacturer: "Dodge",
        model: "Challenger",
        yearOfProduction: 1970,
        purchasePrice: 39.95,
        currentValue: 59.99, 
        preparedtoSell: true,
        qty: 1,
        otherInfo: "2 in 1 kit"
    },
    {
        name: "Shelby Mustang GT 350H",
        brand: "Revell",
        manufacturer: "Ford",
        model: "Mustang",
        yearOfProduction: 1966,
        purchasePrice: 24.95,
        currentValue: 59.99, 
        preparedtoSell: true,
        qty: 1,
    },
    {
        name: "Barracuda",
        brand: "AMT",
        manufacturer: "Plymoth",
        model: "Barradcuda",
        yearOfProduction: 1969,
        purchasePrice: 24.95,
        currentValue: 39.99, 
        preparedtoSell: true,
        qty: 1,
    },
    {
        name: "XC Cobra",
        brand: "Cavalier",
        manufacturer: "Ford",
        model: "XC Cobra",
        yearOfProduction: 1978,
        purchasePrice: 89.95,
        preparedtoSell: true,
        qty: 1,
        otherInfo: "limited edition"
    },
]